# Generated by Django 4.2.4 on 2024-06-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
