# Generated by Django 4.2.4 on 2024-06-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_normal_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff_user',
        ),
    ]
