# Generated by Django 4.2.4 on 2024-06-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_is_normal_user_remove_user_is_staff_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
