# Generated by Django 4.2.4 on 2024-06-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
