version: "3.3"

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./web/src:/app

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./web/src:/app

  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8002
