
build:
	docker-compose build

migrate:
	python3 manage.py makemigrations && python3 manage.py migrate

createsuperuser:
	python3 manage.py createsuperuser

up:
	docker-compose up 

down:
	docker-compose down



